In [1]:
import tensorflow as tf

In [12]:
# Loading the MNIST data

(x_train, y_train), (x_test, y_test) = tf.keras.datasets.mnist.load_data()

In [13]:
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(60000, 28, 28)
(10000, 28, 28)
(60000,)
(10000,)


In [16]:
# Normalization

x_train = x_train/255
x_test  = x_test/255

In [18]:
x_train[0].shape

(28, 28)

In [19]:
# Creating Neural Network Architecture

model = tf.keras.Sequential()
model.add(tf.keras.layers.Flatten(input_shape = x_train[0].shape))
model.add(tf.keras.layers.Dense(524,activation='relu'))
model.add(tf.keras.layers.Dense(128,activation='relu'))
model.add(tf.keras.layers.Dense(10,activation='softmax'))

In [20]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
flatten (Flatten)            (None, 784)               0         
_________________________________________________________________
dense (Dense)                (None, 524)               411340    
_________________________________________________________________
dense_1 (Dense)              (None, 128)               67200     
_________________________________________________________________
dense_2 (Dense)              (None, 10)                1290      
Total params: 479,830
Trainable params: 479,830
Non-trainable params: 0
_________________________________________________________________


In [21]:
# Compiling the Model

model.compile(optimizer='adam',loss='sparse_categorical_crossentropy',metrics='accuracy')

In [22]:
# Training the Model

model.fit(x_train,y_train,epochs=50)

Epoch 1/50
1875/1875 [==============================] - 11s 5ms/step - loss: 0.1847 - accuracy: 0.9441
Epoch 2/50
1875/1875 [==============================] - 10s 5ms/step - loss: 0.0785 - accuracy: 0.9756
Epoch 3/50
1875/1875 [==============================] - 10s 5ms/step - loss: 0.0555 - accuracy: 0.9830
Epoch 4/50
1875/1875 [==============================] - 10s 6ms/step - loss: 0.0405 - accuracy: 0.9868
Epoch 5/50
1875/1875 [==============================] - 10s 6ms/step - loss: 0.0312 - accuracy: 0.9897
Epoch 6/50
1875/1875 [==============================] - 10s 5ms/step - loss: 0.0264 - accuracy: 0.9915
Epoch 7/50
1875/1875 [==============================] - 10s 5ms/step - loss: 0.0219 - accuracy: 0.9926
Epoch 8/50
1875/1875 [==============================] - 10s 5ms/step - loss: 0.0208 - accuracy: 0.9929
Epoch 9/50
1875/1875 [==============================] - 10s 6ms/step - loss: 0.0164 - accuracy: 0.9947
Epoch 10/50
1875/1875 [==============================] - 10s 5ms/step - l

In [33]:
# Evaluating the Model

model.evaluate(x_test, y_test)

313/313 [==============================] - 1s 3ms/step - loss: 0.2123 - accuracy: 0.9822


[0.21226122975349426, 0.982200026512146]

In [34]:
import numpy as np

y_pred = model.predict(x_test)
y_pred = np.argmax(y_pred,axis=1)

In [35]:
y_pred

array([7, 2, 1, ..., 4, 5, 6])

In [36]:
y_test

array([7, 2, 1, ..., 4, 5, 6], dtype=uint8)

In [37]:
from sklearn.metrics import accuracy_score,confusion_matrix
accuracy_score(y_test,y_pred)

0.9822

In [38]:
confusion_matrix(y_pred,y_test)

array([[ 973,    0,    2,    1,    0,    2,    1,    1,    1,    0],
       [   1, 1127,    3,    0,    0,    0,    3,    2,    1,    3],
       [   2,    0, 1010,    5,    4,    0,    0,    6,    5,    0],
       [   0,    2,    1,  989,    0,    7,    0,    0,    7,    3],
       [   0,    0,    1,    0,  965,    0,    1,    1,    2,    8],
       [   1,    1,    0,    9,    1,  880,    5,    1,    9,    3],
       [   2,    2,    3,    0,    4,    1,  946,    0,    2,    1],
       [   1,    1,    7,    4,    1,    0,    0, 1013,    5,   10],
       [   0,    2,    4,    0,    0,    1,    2,    0,  939,    1],
       [   0,    0,    1,    2,    7,    1,    0,    4,    3,  980]])

In [40]:
# Saving the Model

model.save('MNIST.hdf5')